version: '3'
services:
  core-postgres:
    image: postgres:9.6-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=paydex
    ports:
      - "5641:5432"
    volumes:
      - "core-db-data:/var/lib/postgresql/data"
    network_mode: '${NETWORK_MODE:-bridge}'

  core:
    # to use a specific version of paydex core
    # image: paydex/paydex-core:$VERSION
    image: paydex/paydex-core
    depends_on:
      - core-postgres
    restart: always
    ports:
      - "11625:11625"
      - "11626:11626"
    env_file:
      # to connect to the public paydex network
      # - ./paydex-core-pubnet.env
      - ./paydex-core-testnet.env
    command: /start compat_minimal nopsql fresh
    network_mode: '${NETWORK_MODE:-bridge}'

  horizon-postgres:
    image: postgres:9.6-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=horizon
    ports:
      - "5432:5432"
    volumes:
      - "horizon-db-data:/var/lib/postgresql/data"
    network_mode: '${NETWORK_MODE:-bridge}'

  horizon:
    depends_on:
      - horizon-postgres
      - core
    build:
      # set build context to the root directory of the go monorepo
      context: ../../../
      dockerfile: services/horizon/docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres@host.docker.internal:5432/horizon?sslmode=disable
      - PAYDEX_CORE_DATABASE_URL=postgres://postgres:mysecretpassword@host.docker.internal:5641/paydex?sslmode=disable
      # to connect to the public paydex network
      # - NETWORK_PASSPHRASE=Public Global Paydex Network ; September 2015
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - PAYDEX_CORE_URL=http://host.docker.internal:11626
      - INGEST=true
    network_mode: '${NETWORK_MODE:-bridge}'
    command: ["--apply-migrations"]

volumes:
  core-db-data:
  horizon-db-data:
